---
title: Java异常处理机制
date: 2023-07-13
update: 2023-09-16
tags:
categories:
  - Java
  - 类库
keywords: Java,Error,Exception
description: 关于Java异常处理机制
top_img:
cover: https://cdn.jsdelivr.net/gh/ChenXiangcheng1/image-hosting1/img/2023_07_07_13_58.png
---

# Java异常处理机制主要考点



## Throwable 

java.lang.Throwable 类

<img src="https://cdn.jsdelivr.net/gh/ChenXiangcheng1/image-hosting1/img/2023_07_07_13_58.png" style="zoom: 67%;" />

### Error 错误

表示系统错误或低层资源的错误，是程序无法处理的错误，编译器不做检查

从责任角度看：Error 属于 JVM 应该承担的责任，例如处理 JVM 相关的问题、OOM、SOF

* NoClassDefFoundError - 找不到 class 定义的异常
  * NoClassDefFoundError - 的成因：
    * 类依赖的 class 或者 jar 不存在。例如 maven 漏引了某个 jar 包
    * 类文件存在，但是存在不同域中。例如多个不同的 classloader 重复加载了同一个 class
    * 大小写问题，因为 javac 编译时是无视大小写的，很有可能编译出来的 class 文件就与想要的不一样

* SOF(StackOverflowError) - 深递归导致栈被耗尽而抛出的异常

* OOM(OutOfMemoryError) - 内存溢出异常







### Exception 异常

是程序可以处理的异常，捕获后可能恢复。



#### RuntimeException

运行时异常需要在编写代码时避免发生，可抛出异常或捕获异常输出到日志

从责任角度看：RuntimeException 属于开发者应该承担的责任，例如处理数组下标越界、空指针

* NullPointerException - 空指针引用异常
* ClassCastException - 类型强制转换异常
* IllegalArgumentException - 传递非法参数异常
* IndexOutOfBoundsException - 下标越界异常
* NumberFormatException - 数字格式异常
* NoSuchElementException - 集合找不到任何元素异常





#### CheckedException

可预知的，不能通过编译器校验的

从责任角度看：Checked Exception 属于 Java 编译器应该承担的责任，例如 IOException、SQLException

* ClassNotFoundException - 找不到指定 class 的异常
* IOException IO - 操作异常



##### throw/throws 抛出异常

创建异常对象，交由运行时系统处理

异常类型type、异常信息message(**说明产生异常的原因**)、异常堆栈跟踪(抛出异常的位置)
应该尽早throw抛出异常，便于精确定位问题
应该延迟try-catch捕获和处理异常，让掌握更多信息的作用域来处理异常 (即让上层具体的业务类来处理异常)



##### try-catch-finally 捕获异常

捕获异常：寻找合适的异常处理器处理异常，否则终止运行

```java
public class ExceptionHandleMechanism {
    public static int doWork() {
        try {
            int i = 10 / 0;  // 会抛出异常：try语句块执行路径被终止进入异常处理
            System.out.println("try");
        } catch (ArithmeticException e) {  // 捕获ArithmeticException异常
            System.out.println("捕获ArithmeticException:" + e);
            return 0;
        } catch (Exception e) {  // 捕获Exception异常
            System.out.println("Exception:" + e);
            return 1;
        } finally {
            System.out.println("进入Finally");
            return 2;
    }	}
    public static void main(String[]args) {
        System.out.println("方法返回，" + doWork());
}	}
```

```运行
捕获ArithmeticException:java.lang.ArithmeticException: / by zero
进入Finally
方法返回，0  // 从第一个catch捕获处返回
```



###### 性能探讨

```java
public class ExceptionPerformance {
    public static void testException(String[] array) {
        try {
            System.out.println(array[0]);
        } catch (NullPointerException e) {
            System.out.println("array cannot be null");
    }	}
    public static void testIf(String[] array) {
        if (array != null) {
            System.out.println(array[0]);
        } else {
            System.out.println("array cannot be null");
    }	}
    public static void main(String[] args) {
        long start = System.nanoTime();
        testException(null);
        // testIf(null);
        System.out.println("cost " + (System.nanoTime()-start));
}	}
```

```运行
try-catch cost 300400
if cost 174700
```

```java
  public static void testException(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=3, locals=2, args_size=1
         0: getstatic     #7	// 获取out字段 java/lang/System.out:Ljava/io/PrintStream;
         3: aload_0
         4: iconst_0
         5: aaload
         6: invokevirtual #13	// 调用println方法 java/io/PrintStream.println:(Ljava/lang/String;)V
         9: goto          21	// catch
        12: astore_1		 	// 需要存储	// try-catch			
        13: getstatic     #7	// 获取out字段 java/lang/System.out:Ljava/io/PrintStream;
        16: ldc           #21	// String array cannot be null
        18: invokevirtual #13	// 调用println方法 java/io/PrintStream.println:(Ljava/lang/String;)V
        21: return
      Exception table:			// 
         from    to  target type
             0     9    12   Class java/lang/NullPointerException
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
           13       8     1     e   Ljava/lang/NullPointerException;  //
            0      22     0 array   [Ljava/lang/String;
      StackMapTable: number_of_entries = 2
        frame_type = 76 /* same_locals_1_stack_item */
          stack = [ class java/lang/NullPointerException ]  // 
        frame_type = 8 /* same */
```

```java
  public static void testIf(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=3, locals=1, args_size=1
         0: aload_0
         1: ifnull        16	// if array != null  // if-else
         4: getstatic     #7	// 获取out字段 java/lang/System.out:Ljava/io/PrintStream;
         7: aload_0
         8: iconst_0
         9: aaload
        10: invokevirtual #13	// 调用println方法 java/io/PrintStream.println:(Ljava/lang/String;)V
        13: goto          24	// else
        16: getstatic     #7	// 获取out字段 java/lang/System.out:Ljava/io/PrintStream;
        19: ldc           #21	// String array cannot be null
        21: invokevirtual #13	// 调用println方法 java/io/PrintStream.println:(Ljava/lang/String;)V
        24: return
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      25     0 array   [Ljava/lang/String;
      StackMapTable: number_of_entries = 2
        frame_type = 16 /* same */
        frame_type = 7 /* same */
```

try-catch 块会影响 JVM 的优化
异常对象 exception 需要保存栈快照等信息，开销较大
所以 try-catch 效率没有 if-else、switch 高
所以开发者需要仅捕获可能出现异常的代码段、**不要利用异常控制代码流程**



##### try-with-resources 

try -with-resources 语句是声明一个或多个资源的 try 语句，能确保每个资源在语句结束时关闭，任何实现 `java.lang.AutoCloseable` 的对象都可以用作资源。

如果关闭资源时发生异常(`resource.close()` 异常则会造成 resource 泄漏，导致系统资源的浪费)，该异常将被抑制(suppressed)，而不会中断其他异常的抛出。这样可以确保其他异常能够继续传播，同时不丢失资源关闭时的异常信息。(若 `finally` 块中 `resource.close()` 异常，会遮蔽在 `try` 块中发生的异常，所以 `try -with-resources` 更好)

try -with-resources 优点：**简洁、抑制异常**

```java
try (Resource resource1 = new Resource1();
     Resource resource2 = new Resource2()) {
    // do something...
} catch (Exception e) {    
    Throwable[] suppressed = e.getSuppressed();
    for (Throwable throwable : suppressed) {
        // 处理抑制异常...
    }
    // 处理主异常...
}
```



## 异常处理框架

### 自定义异常

<img src="https://cdn.jsdelivr.net/gh/ChenXiangcheng1/image-hosting1/img/2023_07_07_18_12.png" alt="image-20230707181239287" style="zoom:80%;" />

设计一个通用异常类 AppException(继承RuntimeException)来统一处理
在捕获到异常后，抛出通用异常的子类，并提供足以定位的信息
由前端接收 AppException 做统一处理



### Spring 的异常框架设计

Spring 的异常框架设计：org.springframework.core.NestedRuntimeException





# 未整理

抛出异常的两种区别
情况一，用catch抓住异常：
	public Date strToDate(String dateStr) {
 	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
 	Date date = null;
 	try {
  		date = sdf.parse(dateStr);
 	} catch (ParseException e) {
  		e.printStackTrace();
 	}
 		return date;
	}

情况二，用throws抛出异常：
	public Date strToDate(String dateStr) throws ParseException {
 	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
 		return sdf.parse(dateStr);
	}

这两种情况的区别，就在于方法设计的功能实现不同
	情况一要求这个方法能够处理字符串格式不对的例外
	而情况二只要求这个方法转换格式，对于字符串格式不对的例外，只需要把这个“例外”告诉上层调用它的方法就行了
比较形像的描述就是：
	方法一：你给我一个字符串，我看看它格式对不对，如果不对，就返回给你一个null；如果格式对了，就返回给你正确日期。
	方法二：你给我一个字符串，我就返回正确日期；如果格式有问题，我就喊一声“格式有问题！”。
这里的throws，就相当于实现了“喊一声”的功能。


之所以要异常捕获抛出机制，是因为这个类的parse方法对自身的参数有要求，如果不符合格式就会产生异常，即就需要抛出或者捕获 
